import jsPDF from "jspdf";

export interface MethodCertificateData {
  drug: string;
  scientistName: string;
  email: string;
  company: string;
  instrument: string;
  methodId: string;
  timestamp: string;
  fingerprint: string;
  column: string;
  mobilePhase: string;
  flowRate: string;
  detection: string;
  runtime: string;
}

export function generateMethodPdf(data: MethodCertificateData) {
  const doc = new jsPDF("p", "mm", "a4");

  const marginLeft = 15;
  let y = 15;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("LCForge AI – Chromatography Method Certificate (Demo)", marginLeft, y);

  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Method ID: ${data.methodId}`, marginLeft, y);
  y += 5;
  doc.text(`Generated on: ${new Date(data.timestamp).toLocaleString()}`, marginLeft, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Generated For", marginLeft, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(`Scientist: ${data.scientistName || "N/A"}`, marginLeft, y);
  y += 5;
  doc.text(`Company: ${data.company || "N/A"}`, marginLeft, y);
  y += 5;
  doc.text(`Email: ${data.email || "N/A"}`, marginLeft, y);
  y += 5;
  doc.text(`Instrument: ${data.instrument || "N/A"}`, marginLeft, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Method Summary", marginLeft, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(`Drug: ${data.drug}`, marginLeft, y);
  y += 5;
  doc.text(`Column: ${data.column}`, marginLeft, y);
  y += 5;
  doc.text(`Mobile phase: ${data.mobilePhase}`, marginLeft, y);
  y += 5;
  doc.text(`Flow rate: ${data.flowRate}`, marginLeft, y);
  y += 5;
  doc.text(`Detection: ${data.detection}`, marginLeft, y);
  y += 5;
  doc.text(`Run time: ${data.runtime}`, marginLeft, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Confidentiality & Fingerprint", marginLeft, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  const noticeLines = doc.splitTextToSize(
    "This chromatographic method is generated exclusively for the above user by LCForge AI (demo). This method is confidential and reserved for the requesting organization.",
    180
  );
  doc.text(noticeLines, marginLeft, y);
  y += noticeLines.length * 5;

  y += 3;
  doc.text(`Method fingerprint (demo): ${data.fingerprint}`, marginLeft, y);

  // Watermark
  doc.setFontSize(40);
  doc.setTextColor(200, 200, 200);
  doc.text("Generated by LCForge AI", 20, 150, { angle: 30 });

  // Reset text color
  doc.setTextColor(0, 0, 0);

  doc.save(`LCForge-Method-${data.methodId}.pdf`);
}
