import { jsPDF } from "jspdf";

export interface MethodCertificateData {
  drug: string;
  scientistName: string;
  email: string;
  company: string;
  instrument: string;
  methodId: string;
  timestamp: string | number | undefined;
  fingerprint: string;
  column: string;
  mobilePhase: string;
  flowRate: string;
  detection: string;
  runtime: string;
  literature: any[];
  properties: Record<string, any>;
}

export function generateMethodPdf(data: MethodCertificateData) {
  const doc = new jsPDF("p", "mm", "a4");

  // Safely format the timestamp to avoid "Invalid Date"
  let dateStr: string;
  try {
    const raw = (data as any).timestamp;
    const d =
      raw === undefined || raw === null
        ? new Date()
        : new Date(String(raw));
    dateStr = isNaN(d.getTime())
      ? new Date().toLocaleString()
      : d.toLocaleString();
  } catch {
    dateStr = new Date().toLocaleString();
  }

  const marginLeft = 15;
  let y = 15;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("LCForge AI – Chromatography Method Certificate", marginLeft, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Method ID: ${data.methodId}`, marginLeft, y);
  y += 5;
  doc.text(`Generated on: ${dateStr}`, marginLeft, y);
  y += 8;

  // Generated for
  doc.setFont("helvetica", "bold");
  doc.text("Generated For", marginLeft, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(`Scientist: ${data.scientistName || "N/A"}`, marginLeft, y);
  y += 5;
  doc.text(`Company: ${data.company || "N/A"}`, marginLeft, y);
  y += 5;
  doc.text(`Email: ${data.email || "N/A"}`, marginLeft, y);
  y += 5;
  doc.text(`Instrument: ${data.instrument || "N/A"}`, marginLeft, y);
  y += 8;

  // Method summary
  doc.setFont("helvetica", "bold");
  doc.text("Method Summary", marginLeft, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.text(`Drug: ${data.drug}`, marginLeft, y);
  y += 5;
  doc.text(`Column: ${data.column}`, marginLeft, y);
  y += 5;
  doc.text(`Mobile phase: ${data.mobilePhase}`, marginLeft, y);
  y += 5;
  doc.text(`Flow rate: ${data.flowRate}`, marginLeft, y);
  y += 5;
  doc.text(`Detection: ${data.detection}`, marginLeft, y);
  y += 5;
  doc.text(`Run time: ${data.runtime}`, marginLeft, y);
  y += 8;

  // --- Physicochemical properties section ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Physicochemical properties", marginLeft, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const props = (data as any).properties || {};

  if (props.chemical_name) {
    doc.text(`Chemical name: ${props.chemical_name}`, marginLeft, y);
    y += 5;
  }
  if (props.chemical_formula) {
    doc.text(`Formula: ${props.chemical_formula}`, marginLeft, y);
    y += 5;
  }
  if (props.molecular_weight) {
    doc.text(
      `Molecular weight: ${props.molecular_weight}`,
      marginLeft,
      y
    );
    y += 5;
  }
  if (props.pKa) {
    doc.text(`pKa: ${props.pKa}`, marginLeft, y);
    y += 5;
  }
  if (props.solubility) {
    doc.text(`Solubility: ${props.solubility}`, marginLeft, y);
    y += 5;
  }
  if (props.stability) {
    doc.text(`Stability: ${props.stability}`, marginLeft, y);
    y += 5;
  }

  // --- Literature section ---
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Related literature", marginLeft, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const lit = (data as any).literature || [];

  if (Array.isArray(lit) && lit.length > 0) {
    lit.slice(0, 3).forEach((ref: any, idx: number) => {
      const title = ref.title || "Untitled";
      const journal = ref.journal ? ` — ${ref.journal}` : "";
      const year = ref.year ? ` (${ref.year})` : "";
      const authors = ref.authors ? ` · ${ref.authors}` : "";
      const line = `${idx + 1}. ${title}${journal}${year}${authors}`;

      const lines = doc.splitTextToSize(line, 180 - marginLeft);
      doc.text(lines, marginLeft, y);
      y += lines.length * 5;
    });
  } else {
    doc.text(
      "No literature suggestions available for this query.",
      marginLeft,
      y
    );
    y += 5;
  }

  // Confidentiality & Fingerprint
  y += 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Confidentiality & Fingerprint", marginLeft, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const noticeLines = doc.splitTextToSize(
    "This chromatographic method is generated exclusively for the above user by LCForge AI. This method is confidential and reserved for the requesting organization.",
    180
  );
  doc.text(noticeLines, marginLeft, y);
  y += noticeLines.length * 5;

  y += 3;
  doc.text(`Method fingerprint: ${data.fingerprint}`, marginLeft, y);

  // Watermark
  doc.setFontSize(40);
  doc.setTextColor(200, 200, 200);
  doc.text("Generated by LCForge AI", 20, 150, { angle: 30 });

  // Reset text color
  doc.setTextColor(0, 0, 0);

  doc.save(`LCForge-Method-${data.methodId}.pdf`);
}